# Generated by Django 4.2.4 on 2023-09-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created'], 'verbose_name': 'Tienda', 'verbose_name_plural': 'Sabores'},
        ),
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Precio'),
        ),
    ]
